M48
; DRILL file {KiCad (6.0.9)} date Wed Jan 25 05:40:34 2023
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-01-25T05:40:34+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.9)
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
INCH
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.0236
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.0276
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T3C0.0354
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T4C0.0433
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T5C0.0598
%
G90
G05
T1
X5.1Y-3.4
X5.1409Y-3.7
X5.1591Y-3.4
X5.2Y-3.7
T2
X5.4Y-3.9
X5.4Y-4.1
T3
X5.6Y-3.9697
X5.7Y-3.9697
T4
X4.3Y-3.3
X4.3Y-4.1
X4.7Y-3.3
X4.7Y-3.5
X4.7Y-3.9
X4.7Y-4.1
X4.9Y-3.4
X4.9Y-3.8
X4.9Y-4.1
X5.0Y-4.1
X5.1Y-4.1
T5
X4.4Y-3.6
X4.4Y-3.8
X5.5Y-3.4
X5.5Y-3.6
T0
M30
